# Generated by Django 5.0.3 on 2024-03-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='mi_campo',
        ),
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
