# Generated by Django 5.0.3 on 2024-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_mi_campo_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dwrepuhjc/image/upload/v1710643135/4092564-about-mobile-ui-profile-ui-user-website_114033_n9u99c.png'),
        ),
    ]
