# Generated by Django 5.0.3 on 2024-06-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dwrepuhjc/image/upload/v1713576528/blank-profile-picture-973460_640_v8ejyd.png'),
        ),
    ]
