# Generated by Django 5.0.3 on 2024-04-15 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_image',
            field=models.ManyToManyField(blank=True, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
