# Generated by Django 5.0.3 on 2024-04-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_post_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_image',
        ),
    ]
